version : '2'

services:

  redis:
    container_name: sentry-redis
    image: redis

  postgres:
    image: postgres
    container_name: sentry-postgres
    volumes:
      - ./share/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DBNAME: sentry
      POSTGRES_DBUSER: sentry
      POSTGRES_DBPASS: sentry

  sentry:
    container_name: sentry-www
    image: sentry
    ports:
     - 9050:9000
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    environment:
      SENTRY_SECRET_KEY: abcdefghijklmnopqarstuwxyz0123456789
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry

  cron:
    container_name: sentry-cron
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: abcdefghijklmnopqarstuwxyz0123456789
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry

  worker:
    container_name: sentry-worker
    image: sentry
    links:
     - redis
     - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: abcdefghijklmnopqarstuwxyz0123456789
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      C_FORCE_ROOT: 1

  cyclops:
    container_name: sentry-cyclops
    build: ./cyclops
    volumes:
      - ./cyclops:/ggg
