version : '2'

services:

  redis:
    container_name: sentry-redis
    image: redis

  postgres:
    image: postgres
    container_name: sentry-postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: sentry

  sentry:
    container_name: sentry
    image: sentry
    command: bash /bootstrap/sentry.sh
    volumes:
      - ./bootstrap:/bootstrap
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry